2018-04-24 15:07:38.592 - pyansibleinv -        dbbackup_mysql_list -  INFO - args:{'--cluster_id': None,
 '--data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57',
 '--dbfqdn': 'dcs-db-c00aee9f.iad1',
 '--dbtype': 'mysql',
 '--ssh_try_limit': '600',
 '--sshkey': '/opt/ansible/db.pem',
 '--sshpass': 'LR1!Ika',
 '--taskid': None,
 '--template_only': False,
 '--workdir': '/opt/ansible',
 'dbbackup': True,
 'debug': False,
 'list': True}
2018-04-24 15:07:38.592 - pyansibleinv -        dbbackup_mysql_list -  INFO - dict:{'ssh_try_limit': '600', 'workdir': '/opt/ansible', 'sshkey': '/opt/ansible/db.pem', 'template_only': False, 'dbtype': 'mysql', 'backup': True, 'taskid': None, 'task_id': '  external_task_id: db345385-97b7-42d0-8d75-8f4370bd3ae5\n', 'st': True, 'cluster_id': None, 'sshpass': 'LR1!Ika', 'dbfqdn': 'dcs-db-c00aee9f.iad1', 'data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57', 'bug': False, 'uuid': 'db345385-97b7-42d0-8d75-8f4370bd3ae5'}
2018-04-24 15:07:38.593 - pyansibleinv -        dbbackup_mysql_list -  INFO - create ansible hosts: /opt/ansible/inventory/db345385-97b7-42d0-8d75-8f4370bd3ae5/hosts
2018-04-24 15:07:38.593 - pyansibleinv -        dbbackup_mysql_list -  INFO - craete ansible playbooks: /opt/ansible/dbbackup_mysql_list_db345385-97b7-42d0-8d75-8f4370bd3ae5.yml
2018-04-24 15:07:38.595 - pyansibleinv -        dbbackup_mysql_list -  INFO - check ssh availability
2018-04-24 15:07:38.595 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:07:38.663 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:07:38.664 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:07:38.730 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:07:38.730 - pyansibleinv -        dbbackup_mysql_list -  INFO - run ansible from python
2018-04-24 15:07:39.351 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:07:39.351 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - PLAY [list backup sets] ***********************************************************************************************************************************************************************
2018-04-24 15:07:40.108 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:07:40.108 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - TASK [list mysql backup set] ******************************************************************************************************************************************************************
2018-04-24 15:07:42.842 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;33mchanged: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:07:43.563 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:07:43.563 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - TASK [Record backup result] *******************************************************************************************************************************************************************
2018-04-24 15:07:43.775 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:07:43.797 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:07:43.797 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - PLAY RECAP ************************************************************************************************************************************************************************************
2018-04-24 15:07:43.797 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;33mdcs-db-c00aee9f.iad1[0m       : [0;32mok=2   [0m [0;33mchanged=1   [0m unreachable=0    failed=0
2018-04-24 15:07:43.898 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - --- Total Excution time: 0:00:05.306539 ---
2018-04-24 15:07:43.939 - pyansibleinv - dbbackup_mysql_list_stderr - ERROR - {'dcs-db-c00aee9f.iad1': {u'backup_set02': {u'2018_04_23-07_45_55': {u'incrementals': [{u'2018_04_23-09_41_33': {u'size': u'2.9 MB'}}, {u'2018_04_23-09_41_19': {u'size': u'4.6 MB'}}], u'size': u'2.1 GB'}, u'total_szie': u'2.1 GB'}, u'backup_set01': {u'2018_04_23-09_42_05': {u'incrementals': [], u'size': u'2.1 GB'}, u'total_szie': u'2.1 GB'}}}
