2018-04-24 15:08:53.225 - pyansibleinv -        dbbackup_mysql_list -  INFO - args:{'--cluster_id': None,
 '--data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57',
 '--dbfqdn': 'dcs-db-c00aee9f.iad1',
 '--dbtype': 'mysql',
 '--ssh_try_limit': '600',
 '--sshkey': '/opt/ansible/db.pem',
 '--sshpass': 'LR1!Ika',
 '--taskid': None,
 '--template_only': False,
 '--workdir': '/opt/ansible',
 'dbbackup': True,
 'debug': False,
 'list': True}
2018-04-24 15:08:53.225 - pyansibleinv -        dbbackup_mysql_list -  INFO - dict:{'ssh_try_limit': '600', 'workdir': '/opt/ansible', 'sshkey': '/opt/ansible/db.pem', 'template_only': False, 'dbtype': 'mysql', 'backup': True, 'taskid': None, 'task_id': '  external_task_id: 50cc646f-13c6-447c-8568-b9a23c05a6dd\n', 'st': True, 'cluster_id': None, 'sshpass': 'LR1!Ika', 'dbfqdn': 'dcs-db-c00aee9f.iad1', 'data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57', 'bug': False, 'uuid': '50cc646f-13c6-447c-8568-b9a23c05a6dd'}
2018-04-24 15:08:53.225 - pyansibleinv -        dbbackup_mysql_list -  INFO - create ansible hosts: /opt/ansible/inventory/50cc646f-13c6-447c-8568-b9a23c05a6dd/hosts
2018-04-24 15:08:53.226 - pyansibleinv -        dbbackup_mysql_list -  INFO - craete ansible playbooks: /opt/ansible/dbbackup_mysql_list_50cc646f-13c6-447c-8568-b9a23c05a6dd.yml
2018-04-24 15:08:53.228 - pyansibleinv -        dbbackup_mysql_list -  INFO - check ssh availability
2018-04-24 15:08:53.228 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:08:53.294 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:08:53.295 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:08:53.362 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:08:53.363 - pyansibleinv -        dbbackup_mysql_list -  INFO - run ansible from python
2018-04-24 15:08:53.976 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:08:53.976 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - PLAY [list backup sets] ***********************************************************************************************************************************************************************
2018-04-24 15:08:54.723 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:08:54.724 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - TASK [list mysql backup set] ******************************************************************************************************************************************************************
2018-04-24 15:08:57.659 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;33mchanged: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:08:58.388 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:08:58.388 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - TASK [Record backup result] *******************************************************************************************************************************************************************
2018-04-24 15:08:58.640 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:08:58.661 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:08:58.661 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - PLAY RECAP ************************************************************************************************************************************************************************************
2018-04-24 15:08:58.661 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;33mdcs-db-c00aee9f.iad1[0m       : [0;32mok=2   [0m [0;33mchanged=1   [0m unreachable=0    failed=0
2018-04-24 15:08:58.705 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - --- Total Excution time: 0:00:05.480108 ---
2018-04-24 15:08:58.747 - pyansibleinv - dbbackup_mysql_list_stderr - ERROR - {"dcs-db-c00aee9f.iad1": {"backup_set02": {"2018_04_23-07_45_55": {"incrementals": [{"2018_04_23-09_41_33": {"size": "2.9 MB"}}, {"2018_04_23-09_41_19": {"size": "4.6 MB"}}], "size": "2.1 GB"}, "total_szie": "2.1 GB"}, "backup_set01": {"2018_04_23-09_42_05": {"incrementals": [], "size": "2.1 GB"}, "total_szie": "2.1 GB"}}}
